### PR TITLE
OTG Test Update - TE 11.2 Loss Pct fix

### LINKED ISSUE #646: OTG: TE-11.2: Backup NHG: Multiple NH

### PR DESCRIPTION
**Pull request by octpetre**
This is required for the correct packet loss telemetry.
`gnmi.Get(t, ate.OTG(), flowPath.LossPct().State())` not yet supported on OTG.
Fixes #646

### CODE REVIEW

**Review by greg-dennis — APPROVED** [review]

File: feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go [hunk 1]
```diff
@@ -313,15 +315,16 @@ func validateTrafficFlows(t *testing.T, ate *ondatra.ATEDevice, ateTop gosnappi.
 	ate.OTG().StopTraffic(t)
 	otgutils.LogFlowMetrics(t, ate.OTG(), ateTop)
 	otgutils.LogPortMetrics(t, ate.OTG(), ateTop)
-	flowPath := gnmi.OTG().Flow(flow)
-	got := gnmi.Get(t, ate.OTG(), flowPath.LossPct().State())
+	recvMetric := gnmi.Get(t, ate.OTG(), gnmi.OTG().Flow(flow).State())
+	lostPackets := recvMetric.GetCounters().GetOutPkts() - recvMetric.GetCounters().GetInPkts()
+	got := lostPackets * 100 / recvMetric.GetCounters().GetOutPkts()
```
Comment (jasdeep-hundal) [inline feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go:320]: Make this a floating point result.

File: feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go [hunk 2]
```diff
@@ -313,15 +315,16 @@ func validateTrafficFlows(t *testing.T, ate *ondatra.ATEDevice, ateTop gosnappi.
...
 	if drop {
 		if got != 100 {
-			t.Fatalf("Traffic passing for flow %s got %f, want 100 percent loss", flow, got)
+			t.Fatalf("Traffic passing for flow %s got %v, want 100 percent loss", flow, got)
```
Comment (jasdeep-hundal) [inline feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go:323]: What's the reason for changing from a %f?

File: feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go [hunk 3]
```diff
@@ -61,7 +62,7 @@ var (
 	}
 
 	atePort1 = attrs.Attributes{
-		Name:    "atePort1",
+		Name:    "port1",
```
Comment (jasdeep-hundal) [inline feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go:65]: Why the change in name here?

File: feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go [hunk 4]
```diff
@@ -333,6 +336,8 @@ func flapinterface(t *testing.T, dut *ondatra.DUTDevice, port string, action boo
 	dc := gnmi.OC()
 	i := &oc.Interface{}
 	i.Enabled = ygot.Bool(action)
+	i.Type = ethernetCsmacd
```
Comment (jasdeep-hundal) [inline feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go:339]: Worth a comment on why setting Type/Name is needed in the 'flap' function.

**Review by jasdeep-hundal — CHANGES_REQUESTED** [review]

File: feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go (hunk 3 above)
Comment (octpetre) [reply feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go:65]: Restored the original names. I changed the name of the source port in the createFlow function, which is always "port1"

File: feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go (hunk 1 above)
Comment (octpetre) [reply feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go:320]: Done

File: feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go (hunk 2 above)
Comment (octpetre) [reply feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go:323]: Done..."got" is not floating point

File: feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go (hunk 4 above)
Comment (octpetre) [reply feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go:339]: Some vendors require these to be set

File: feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go [hunk 5]
```diff
@@ -313,15 +315,16 @@ func validateTrafficFlows(t *testing.T, ate *ondatra.ATEDevice, ateTop gosnappi.
 	ate.OTG().StopTraffic(t)
 	otgutils.LogFlowMetrics(t, ate.OTG(), ateTop)
 	otgutils.LogPortMetrics(t, ate.OTG(), ateTop)
-	flowPath := gnmi.OTG().Flow(flow)
-	got := gnmi.Get(t, ate.OTG(), flowPath.LossPct().State())
+	recvMetric := gnmi.Get(t, ate.OTG(), gnmi.OTG().Flow(flow).State())
+	lostPackets := recvMetric.GetCounters().GetOutPkts() - recvMetric.GetCounters().GetInPkts()
+	got := float32(lostPackets * 100 / recvMetric.GetCounters().GetOutPkts())
```
Comment (jasdeep-hundal) [inline feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go:320]: We need to cast `lostPackets` and `recvMetric.GetCounters().GetOutPkts()` individually, otherwise the calculation inside the parentheses is still going to result in an integer value.)

**Review by jasdeep-hundal — CHANGES_REQUESTED** [review]

File: feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go (hunk 5 above)
Comment (octpetre) [reply feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go:320]: Code changed

File: feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go [hunk 6]
```diff
@@ -316,8 +316,13 @@ func validateTrafficFlows(t *testing.T, ate *ondatra.ATEDevice, ateTop gosnappi.
...
 	recvMetric := gnmi.Get(t, ate.OTG(), gnmi.OTG().Flow(flow).State())
-	lostPackets := recvMetric.GetCounters().GetOutPkts() - recvMetric.GetCounters().GetInPkts()
-	got := float32(lostPackets * 100 / recvMetric.GetCounters().GetOutPkts())
+	txPackets := recvMetric.GetCounters().GetOutPkts()
+	rxPackets := recvMetric.GetCounters().GetInPkts()
+	lostPackets := txPackets - rxPackets
+	if txPackets == 0 {
+		t.Fatalf("Tx packets should be higher than 0")
+	}
+	got := float32(lostPackets * 100 / txPackets)
```
Comment (jasdeep-hundal) [inline feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go:325]: Still need a cast before the division here, else we are just getting an integer value back anyways.

**Review by jasdeep-hundal — CHANGES_REQUESTED** [review]

File: feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go (hunk 6 above)
Comment (octpetre) [reply feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go:325]: Made txPackets and rxPackets float32

**Review by jasdeep-hundal — APPROVED** [review]

File: feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go [hunk 7]
```diff
@@ -333,11 +341,14 @@ func flapinterface(t *testing.T, dut *ondatra.DUTDevice, port string, action boo
 	dc := gnmi.OC()
 	i := &oc.Interface{}
 	i.Enabled = ygot.Bool(action)
+	i.Type = ethernetCsmacd
+	i.Name = ygot.String(dutP.Name())
```
Comment (jasdeep-hundal) [inline feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go:345]: @octpetre : These are the only changes that need to be incorporated now.

**Review by jasdeep-hundal — CHANGES_REQUESTED** [review]
@octpetre : There have been deeper updates to the OTG test file, most of these changes are no longer needed.

File: feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go [hunk 8]
```diff
@@ -381,21 +383,24 @@ func (a *testArgs) validateTrafficFlows(t *testing.T, flow string, expected_outg
 	otgutils.LogPortMetrics(t, a.ate.OTG(), a.top)
 	// Get send traffic
 	incoming_traffic_counters := gnmi.OC().Interface(a.ate.Port(t, "port1").Name()).Counters()
-	sentPkts := gnmi.Get(t, a.ate, incoming_traffic_counters.OutPkts().State())
+	sentPkts := gnmi.Get(t, a.ate.OTG(), incoming_traffic_counters.OutPkts().State())
```
Comment (jasdeep-hundal) [inline feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go:386]: Needs to use port ID instead of name here and then a slightly different path here (as well for the out packet counts below):
```
incoming_traffic_state := gnmi.OTG().Port(a.ate.Port(t, "port1").ID()).State()
sentPkts := gnmi.Get(t, a.ate.OTG(), incoming_traffic_state).GetCounters().GetOutFrames()
```

**Review by jasdeep-hundal — CHANGES_REQUESTED** [review]

File: feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go (hunk 8 above)
Comment (octpetre) [reply feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go:386]: Corrected

**Review by jasdeep-hundal — APPROVED** [review]
